apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgsql-pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/k8s-data/pgsql-db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-pv-claim
  labels:
    app: pgsql-db
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: db
    environment: backend
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
      environment: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: db
        environment: backend
    spec:
      containers:
      - image: postgres:latest
        name: postgres
        env:
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_PASSWORD
          value: password1!
        - name: POSTGRES_DB
          value: postgres
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"
        volumeMounts:
        - name: pgsql-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pgsql-persistent-storage
        persistentVolumeClaim:
          claimName: pgsql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
    environment: backend
spec:
  ports:
    - port: 5432
  selector:
    app: db
    environment: backend
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-pv-volume
  labels:
    app: odoo-app
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/k8s-data/odoo-app"
---
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-addons-pv-volume
  labels:
    app: odoo-addons
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/k8s-data/odoo-addons"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-addons-pv-claim
  labels:
    app: odoo-addons
spec:
  selector:
    matchLabels:
      app: odoo-addons
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-pv-claim
  labels:
    app: odoo-app
spec:
  selector:
    matchLabels:
      app: odoo-app
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: odoo-app
  name: odoo-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8069
  selector:
    app: odoo
    environment: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: odoo
    environment: frontend
  name: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
      environment: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: odoo
        environment: frontend
    spec:
      containers:
      - image: donevgoran/odoo13:latest
        name: odoo
        imagePullPolicy: "Always"
        env:
        - name: HOST
          value: db
        - name: PORT
          value: "5432"
        - name: USER
          value: odoo
        - name: PASSWORD
          value: password1!
        readinessProbe:
          tcpSocket:
            port: 8069
          initialDelaySeconds: 10
          periodSeconds: 60
        livenessProbe:
          httpGet:
            path: /
            port: 8069
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        ports:
          - containerPort: 8069
        volumeMounts:
        - name: odoo-persistent-storage
          mountPath: /var/lib/odoo
        - name: odoo-addons-persistent-storage
          mountPath: /mnt/extra-addons
      volumes:
      - name: odoo-persistent-storage
        persistentVolumeClaim:
          claimName: odoo-pv-claim
      - name: odoo-addons-persistent-storage
        persistentVolumeClaim:
          claimName: odoo-addons-pv-claim
